### PR TITLE
always use latest miniconda version

### PR DESCRIPTION
**Pull request by tzk**

### CODE REVIEW

**Comment by bgruening** [comment]
Is this really needed? It always good to pinpoint to a specific version for reproducibility and to guarantee that nothing breaks in a upstream project, which is awkward to figure out.

**Comment by tzk** [comment]
I think this largely depends on what we want to check with travis.

The current setup installs all the required versions >= just as defined in
setup.py. So all tests are basically run with the latest software that is
available. In this context, using the latest miniconda version matches the
overall strategy.

This basically tests functionality for a user installing everything from
scratch. Sure, one downside is that things will break if there is some
inconsistency with an updated version. This won't be related to any of our
code and is hard to track down.

When we have more tests we should specify detailed install instructions and
fix a set of working versions as well. Once we have done this, we should
naturally run the tests for those versions (and fix the conda version as
well, probably).

On Tue, Nov 24, 2015 at 4:21 PM, Björn Grüning <notifications@github.com>
wrote:

> Is this really needed? It always good to pinpoint to a specific version
> for reproducibility and to guarantee that nothing breaks in a upstream
> project, which is awkward to figure out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabriziocosta/EDeN/pull/52#issuecomment-159302477>.
>



-- 
--------------------------------------------------
Daniel Maticzka, Dipl. Inf.
Lehrstuhl für Bioinformatik
Institut für Informatik
Albert-Ludwigs-Universität Freiburg

Tel: (+49) 761 203 97529
Fax: (+49) 761 203 7462
Mail: maticzkd@informatik.uni-freiburg.de
--------------------------------------------------

**Comment by bgruening** [comment]
@tzk we want to check EDeN right? :)
Here is maybe a counter argument: https://github.com/fabriziocosta/EDeN/pull/54
We need to pinpoint some packages to some versions and API changes will be introduced at any time in upstream packages. setup.py gives you much control over you dependencies, Anaconda does not. So we should fix a version here. This would also be nice to write in the documentation. EDeN is tested with this version of Anaconda.
Just my 5c.

**Comment by tzk** [comment]
Yes, I completely agree. We also have this issue with scikit-learn versions
16 and 17 for example. However we don't actually test much yet, so we do
not know about the expected behavior nor about the required versions. So
currently I simply relicate the setup.py definitions in the travis tests.
Once we have this information and the tests we can fix versions, at least
for the tests.

I'm really not sure about fixing versions in setup.py. If we do this, EDeN
will only ever be able to run with it's own virtual environment because
other packages may require larger versions and may update dependencies also
used by EDeN. I don't know if this is the way to go, what about you guys?
Or do I see too many problems there?

On Thu, Nov 26, 2015 at 1:06 AM, Björn Grüning <notifications@github.com>
wrote:

> @tzk <https://github.com/tzk> we want to check EDeN right? :)
> Here is maybe a counter argument: #54
> <https://github.com/fabriziocosta/EDeN/pull/54>
> We need to pinpoint some packages to some versions and API changes will be
> introduced at any time in upstream packages. setup.py gives you much
> control over you dependencies, Anaconda does not. So we should fix a
> version here. This would also be nice to write in the documentation. EDeN
> is tested with this version of Anaconda.
> Just my 5c.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabriziocosta/EDeN/pull/52#issuecomment-159762965>.
>



-- 
--------------------------------------------------
Daniel Maticzka, Dipl. Inf.
Lehrstuhl für Bioinformatik
Institut für Informatik
Albert-Ludwigs-Universität Freiburg

Tel: (+49) 761 203 97529
Fax: (+49) 761 203 7462
Mail: maticzkd@informatik.uni-freiburg.de
--------------------------------------------------

**Pull request merged**
