### PR TITLE
Python3 Compatibility

### PR DESCRIPTION
**Pull request by rgerkin**
This contains the set of things I needed to do to get Python 3 compatibility for my application.  Most of it was just done with 2to3, and a few things were done manually.  Some of the things may break Python2 compatibility.  I would recommend merging this into a new python3 branch like the one in my repo.

### CODE REVIEW

**Comment by bgruening** [comment]
@rgerkin using a library like https://pypi.python.org/pypi/six would be nice so we can maintain both worlds in the same codebase. EDEN is a fast moving target and a separate python3 branch would be outdated pretty soon.

Most of your list() casts looks unnecessary, especially the once in a for loop. It does not matter if we iterate over a list (python2) or an iterator (python3) isn't it?

**Comment by rgerkin** [comment]
@bgruening Yes many of the list() casts do nothing, but are done automatically by the 2to3 tool in case later code does something like try to access something like dict.items() by index, which is allowed in 2 but not in 3 (except with explicit list() conversion).  Typically the only things that really matter are fixing the imports and the print statements.  

I'll probably just fix any Python 2 incompatibilities manually until the Travis tests pass, and let you know when that happens so you can revisit this PR.  If you pull it at that point, you won't probably won't need to maintain a separate branch for Python 3 since Python3-incompatible changes will be introduced at a very slow rate and can just be patched on the main branch.

**Comment by bgruening** [comment]
Sounds like a plan! We should also get a python3 linter integrated as part of our testing so we force people to write python3 combo code :)

**Comment by rgerkin** [comment]
@bgruening Yeah I'll put 2.7 and 3.5 testing in the .travis file of the new branch.

**Comment by bgruening** [comment]
Awesome! Thanks a lot for this contribution!

**Comment by fabriziocosta** [comment]
new version will address Python3

**Pull request closed without merging**
